---
title: "長庚大學 大數據分析方法 作業三"
output: github_document
---
## 網站資料爬取
```{r}
#這是R Code Chunk
library(rvest)
dfALL<-NULL
for(i in 1:6){
  indexnum<-i
  url<-paste0('https://www.ptt.cc/bbs/NBA/index',indexnum,'.html')
  nbaurl<-read_html(url)
  title<-nbaurl%>%html_nodes('.title a')%>%html_text()
  author<-nbaurl%>%html_nodes('.author')%>%html_text()
  pushnum<-nbaurl%>%html_nodes('.nrec')%>%html_text()
  df<-data.frame(Title=title,PushNUm=pushnum,Author=author)
  dfALL<-rbind(dfALL,df)
}
```

## 爬蟲結果呈現
```{r}
#這是R Code Chunk
knitr::kable(dfALL) ##請將iris取代為上個步驟中產生的爬蟲資料資料框
```

## 解釋爬蟲結果 
```{r}
#這是R Code Chunk
dim(dfALL)
#有120列(120筆資料) 3行(3個欄位)
nrow(dfALL)
#有120列(120筆資料)
str(dfALL)
#dfALL是資料框
AuthorNum<-data.frame(table(dfALL$Author))
colnames(AuthorNum)<-c('作者','文章數')
knitr::kable(AuthorNum)
 
```

共爬出幾篇文章標題?
共爬出120篇標題

哪個作者文章數最多?
120篇文章中,作者Lyotard最多,共23篇

```{r}
#這是R Code Chunk
TitleNum<-data.frame(table(dfALL$Title))
colnames(TitleNum)<-c('標題名稱','重複數量')
knitr::kable(TitleNum)
```

其他爬蟲結果解釋

(1)由表TitleNum看出在120篇文章中,
   Re: [話題] 之所以喜歡國王的理由？
   以及 Re: 如何你是Phil Jackson會怎麼作??
   兩個標題是文章重複數量較高的

(2)由表dfALL觀察出,
   文章:[轉錄]Lyotard 對於太陽板討論串的結論
   作者:Price
   推文數是最高的有27個推文